# Site settings
title: Ah, a Postdoc Blog
email: jburgess@mpe.mpg.de
description: > # this means to ignore newlines until "baseurl:"
  I'm a postdoc at MPE working on the prompt and afterglow emission of
  gamma-ray bursts. My interests also include proper statistical analysis,
  Bayesian modeling, and development of tools to advance multi-wavelength
  astronomy. 
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmichaelburgess.com" # the base hostname & protocol for your site
github_username:  grburgess
permalink: /:title/ #/blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-feed
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
#theme: jekyll-theme-tactile
#theme: minimal-mistakes-jekyll
#theme: minima
